name: kalia

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:

      - name: code checker
        uses: actions/checkout@v3


      - name: image code
        run: |
          docker build -t my-python-script .

      - name: kalia.py runner
        run: |
          docker run my-python-script
          
